### ISSUE TITLE
2425-W-010 Structured data A/B testing

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-score#7]
WO Doc https://docs.google.com/document/d/1P5pGoolySNHCv6Dbxa4DoLCcxaFBs3E2WMtzJYaa-bw/edit#heading=h.phzh70cof3ne

**Comment by saumier** [comment]
@fjjulien This WO is completed. I have emailed Gaëlle to make a demo. Let me know if you have any questions before I close this WO.

**Comment by saumier** [comment]
@tammy-culture Please send final invoice as this WO is closed. Thx.

**Comment by tammy-culture** [comment]
@saumier Done
