### ISSUE TITLE
Artsdata-score workflow broken

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-score#8]
The main workflow `generate_report.yml` re-uses the original Orion workflow which has been removed from Orion in favour of the Artsdata Pipeline Action. 

This workflow needs to be updated to use the Artsdata Pipeline Action. It appears that the Artsdata Pipeline Action does not support the parameter 'save_method: artifact'. Special attention is needed to use Github artifacts when fetching data or else changing the approach.

**Comment by dev-aravind** [comment]
@saumier We are using the commit method to fetch the rdf data and scoring them now. Please review this and let me know if you find any issues.

**Comment by saumier** [comment]
@dev-aravind This is working with Sanderson. So I will close the issue and let Gaëlle know it is available for her to try. Thx.
